export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_PIPELINES_STARTED = 'GET_PIPELINES_STARTED';
export const GET_PIPELINES_COMPLETED = 'GET_PIPELINES_COMPLETED';
export const GET_PIPELINES_FAILED = 'GET_PIPELINES_FAILED';

export const GET_REPOSITORIES_STARTED = 'GET_REPOSITORIES_STARTED';
export const GET_REPOSITORIES_COMPLETED = 'GET_REPOSITORIES_COMPLETED';
export const GET_REPOSITORIES_FAILED = 'GET_REPOSITORIES_FAILED';

export const GET_CUSTOM_PIPELINE_STARTED = 'GET_CUSTOM_PIPELINE_STARTED';
export const GET_CUSTOM_PIPELINE_COMPLETED = 'GET_CUSTOM_PIPELINE_COMPLETED';
export const GET_CUSTOM_PIPELINE_FAILED = 'GET_CUSTOM_PIPELINE_FAILED';

export const ADD_PIPELINE = 'ADD_PIPELINE';
