export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_PIPELINES_STARTED = 'GET_PIPELINES_STARTED';
export const GET_PIPELINES_COMPLETED = 'GET_PIPELINES_COMPLETED';
export const GET_PIPELINES_FAILED = 'GET_PIPELINES_FAILED';

export const GET_REPOSITORIES_STARTED = 'GET_REPOSITORIES_STARTED';
export const GET_REPOSITORIES_COMPLETED = 'GET_REPOSITORIES_COMPLETED';
export const GET_REPOSITORIES_FAILED = 'GET_REPOSITORIES_FAILED';

export const GET_CUSTOM_PIPELINE_STARTED = 'GET_CUSTOM_PIPELINE_STARTED';
export const GET_CUSTOM_PIPELINE_COMPLETED = 'GET_CUSTOM_PIPELINE_COMPLETED';
export const GET_CUSTOM_PIPELINE_FAILED = 'GET_CUSTOM_PIPELINE_FAILED';

export const GET_DASHBOARDS_STARTED = 'GET_DASHBOARDS_STARTED';
export const GET_DASHBOARDS_COMPLETED = 'GET_DASHBOARDS_COMPLETED';
export const GET_DASHBOARDS_FAILED = 'GET_DASHBOARDS_FAILED';

export const ADD_PIPELINE = 'ADD_PIPELINE';
export const DELETE_PIPELINE = 'DELETE_PIPELINE';

export const GET_PGE_LOAD_PROFILE_STARTED = 'GET_PGE_LOAD_PROFILE_STARTED';
export const GET_PGE_LOAD_PROFILE_COMPLETED = 'GET_PGE_LOAD_PROFILE_COMPLETED';
export const GET_PGE_LOAD_PROFILE_FAILED = 'GET_PGE_LOAD_PROFILE_FAILED';

export const ADD_CHART = 'ADD_CHART';
export const REMOVE_CHART = 'REMOVE_CHART';

export const ADD_DASHBOARD = 'ADD_DASHBOARD';
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';

export const SET_CURRENT_DASHBOARD = 'SET_CURRENT_DASHBOARD';
