export const LOGIN_USER_STARTED = 'LOGIN_USER_STARTED';
export const LOGIN_USER_COMPLETED = 'LOGIN_USER_COMPLETED';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
