version: 2.1
orbs:
  node: circleci/node@2.1.1
  python: circleci/python@0.3.2
jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      - PGE_STOP_DATE=7/5/20
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Update PG&E Data
          command: |
            python ./scripts/pgande.py --start 1/1/20 --end $PGE_STOP_DATE
      - node/install:
          node-version: latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Run Lint
          command: |
            npm run lint
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ] ; then
              echo Deploy to Staging...
              npm run deploy-staging-ci
              echo Deploy Complete
            elif [ "${CIRCLE_BRANCH}" == "master" ] ; then
              echo Deploy to Production...
              npm run deploy-production-ci
              echo Deploy Complete
            fi