version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: latest
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ] ; then
              echo Deploy to Staging...
              npm run deploy-staging-ci
              echo Deploy Complete
            elif [ "${CIRCLE_BRANCH}" == "master" ] ; then
              echo Deploy to Production...
              npm run deploy-production-ci
              echo Deploy Complete
            fi
